# This file provides instructions for packaging.

`MooseX-CustomInitArgs`
	perl_version_from m`MooseX::CustomInitArgs`;
	version_from      m`MooseX::CustomInitArgs`;
	readme_from       m`MooseX::CustomInitArgs`;
	requires          p`Data::OptList 0`;
	requires          p`Moose 2.00`;
	test_requires     p`Test::Fatal 0`;
.

