@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/MooseX-CustomInitArgs/project>
	deps:runtime-requirement         [ deps:on "Data::OptList 0"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Moose 2.00"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::Fatal 0"^^deps:CpanId ].

